version: "3.8"

services:
  web:
    build: ./text-summ
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./text-summ:/usr/src/app
    ports:
      - "8004:8000"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      # A container env var for the POSTGRESQL DB_URL:
      #   {db-type}://{user-name}:{password}@{host}:{port}/{db-name}?{parameter1=value}
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
    depends_on:
      - web-db

  web-db:
    build:
      # like the `-f` flag
      context: ./text-summ/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres